# Jekyll configuration for UDMS Lab

title: "Ultrafast Dynamics & Materials Spectroscopy Laboratory"
description: "Inha University UDMS Lab website built with Jekyll"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title/
markdown: kramdown
future: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .gitignore
  - scripts

gems:
  - jekyll-seo-tag
